import { error } from '@sveltejs/kit';
// import type { RequestHandler } from './$types';
import { readFile } from 'node:fs/promises';
import path from 'node:path';

import { env } from '$env/dynamic/private';
import { eq } from 'drizzle-orm';

import { database } from '$lib/database/db';
import { media } from '$lib/database/schema';

const mediaRoot = path.resolve(env.MEDIA_ROOT || '/app/media');

export const GET = async ({ url }) => {
  const imageId = url.searchParams.get('id');

  console.log(imageId);

  const result = await database
    .select()
    .from(media)
    .where(eq(media.id, imageId))
    .limit(1);

  const image = result[0];

  if (!image) {
    error(404, 'Image not found');
  }

  // storageKey should be generated by your application.
  const imagePath = path.resolve(mediaRoot, `${image.eventId}/${image.filename}`);

  // Prevent a bad storage key from escaping /app/media.
  if (
    imagePath !== mediaRoot &&
    !imagePath.startsWith(`${mediaRoot}${path.sep}`)
  ) {
    error(500, 'Invalid image path');
  }

  const file = await readFile(imagePath);

    return new Response(new Uint8Array(file), {
    headers: {
        'Content-Length': String(file.byteLength),
        'Cache-Control': 'public, max-age=86400'
    }
    });
};
